version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: paranormal-distribution-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paranormal_distribution
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: paranormal-distribution-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=paranormal_distribution
      - JWT_SECRET=paranormal_distribution_secret_key
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data: